repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.0
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude --exit-non-zero-on-fix
        language: system
        types: [python]
        exclude: ^app/migrations/versions/.*
        pass_filenames: true

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        language: system
        types: [python]
        exclude: ^app/migrations/versions/.*
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        exclude: ^app/migrations/versions/.*
        pass_filenames: true

      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright
        language: system
        types: [python]
        exclude: ^app/migrations/versions/.*
        pass_filenames: false
